[project]
name = "example-am"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandantic>=1.0.1",
    "pandas>=2.3.3",
    "pydantic>=2.12.4",
]
